export { default as App } from './app'
export { default as Home } from './home'
export { default as About } from './about'
export { default as Doodle } from './doodle'
export { default as Objectified } from './objectified'
export { default as NoMatch } from './no-match'
